Repository NGSGameCamp/BE_Repository, pull requests merged in 2025-09, with the labels that each got.

#15 [chore] gradle에 h2 의존성 추가
  build.gradle
  src/test/resources/application-test.yml
Labels: chore

#24 [refactor] Order, Cart 구조 개선
  .gitignore
  build.gradle
  src/main/java/com/imfine/ngs/_global/config/OpenApiConfig.java
  src/main/java/com/imfine/ngs/_global/config/cors/CorsConfig.java
  src/main/java/com/imfine/ngs/_global/config/cors/CorsProperties.java
  src/main/java/com/imfine/ngs/_global/config/security/SecurityConfig.java
  src/main/java/com/imfine/ngs/order/entity/Game.java
  src/main/java/com/imfine/ngs/order/entity/Order.java
  src/main/java/com/imfine/ngs/order/entity/OrderStatus.java
  src/main/java/com/imfine/ngs/order/service/OrderService.java
  src/main/java/com/imfine/ngs/payment/client/PortOneClient.java
  src/main/java/com/imfine/ngs/payment/dto/PaymentRequest.java
  src/main/java/com/imfine/ngs/payment/dto/PaymentResponse.java
  src/main/java/com/imfine/ngs/payment/entity/Payment.java
  src/main/java/com/imfine/ngs/payment/service/PaymentService.java
  src/main/resources/application.properties
  src/test/java/com/imfine/ngs/NgsApplicationTests.java
  src/test/java/com/imfine/ngs/order/OrderServiceTest.java
  src/test/java/com/imfine/ngs/payment/PaymentServiceTest.java
  src/test/resources/application-test.yml
Labels: refactor

#17 [test] Support Unit Test
  src/main/java/com/imfine/ngs/support/entity/Support.java
  src/main/java/com/imfine/ngs/support/entity/SupportAnswer.java
  src/main/java/com/imfine/ngs/support/entity/SupportCategory.java
  src/main/java/com/imfine/ngs/support/repository/SupportAnswerRepo.java
  src/main/java/com/imfine/ngs/support/repository/SupportCategoryRepo.java
  src/main/java/com/imfine/ngs/support/repository/SupportRepo.java
  src/main/java/com/imfine/ngs/support/service/SupportAnswerService.java
  src/main/java/com/imfine/ngs/support/service/SupportCategoryService.java
  src/main/java/com/imfine/ngs/support/service/SupportService.java
  src/test/java/com/imfine/ngs/support/integration/SupportH2Test.java
  src/test/java/com/imfine/ngs/support/unit/SupportTest.java
Labels: test

#19 [test] Game test
  src/main/java/com/imfine/ngs/game/config/GameConfig.java
  src/main/java/com/imfine/ngs/game/entity/Env.java
  src/main/java/com/imfine/ngs/game/entity/Game.java
  src/main/java/com/imfine/ngs/game/enums/EnvType.java
  src/main/java/com/imfine/ngs/game/enums/GameStatus.java
  src/main/java/com/imfine/ngs/game/enums/SortType.java
  src/main/java/com/imfine/ngs/game/repository/EnvRepository.java
  src/main/java/com/imfine/ngs/game/repository/GameRepository.java
  src/main/java/com/imfine/ngs/game/service/search/GameSearchService.java
  src/test/java/com/imfine/ngs/game/GameSearchTest.java
Labels: test

#37 [fix] 빈 주입
  src/main/java/com/imfine/ngs/user/config/OauthClientConfig.java
  src/main/java/com/imfine/ngs/user/repository/FollowRepository.java
  src/main/java/com/imfine/ngs/user/repository/UserRepository.java
Labels: fix

#51 [test] jwt 로그인 회원가입 테스트
  src/main/java/com/imfine/ngs/_global/config/security/SecurityConfig.java
  src/main/java/com/imfine/ngs/user/dto/request/SignInRequest.java
  src/main/java/com/imfine/ngs/user/dto/request/SignUpRequest.java
  src/main/java/com/imfine/ngs/user/dto/response/SignInResponse.java
  src/main/java/com/imfine/ngs/user/service/AuthService.java
  src/test/java/com/imfine/ngs/user/service/AuthServiceTest.java
  src/test/java/com/imfine/ngs/user/service/ProfileServiceTest.java
Labels: test

#56 [refactor] 게임 환경(ENV)를 String에서 Enum 타입을 사용하도록 수정하였다.
  src/main/java/com/imfine/ngs/game/config/GameConfig.java
  src/main/java/com/imfine/ngs/game/entity/Game.java
  src/main/java/com/imfine/ngs/game/entity/env/Env.java
  src/main/java/com/imfine/ngs/game/entity/env/LinkedEnv.java
  src/main/java/com/imfine/ngs/game/entity/env/util/LinkedEnvId.java
  src/main/java/com/imfine/ngs/game/repository/GameRepository.java
  src/main/java/com/imfine/ngs/game/repository/env/EnvRepository.java
  src/main/java/com/imfine/ngs/game/repository/env/LinkedEnvRepository.java
  src/main/java/com/imfine/ngs/game/service/publisher/GameRegistrationService.java
  src/main/java/com/imfine/ngs/game/service/search/GameSearchService.java
  src/test/java/com/imfine/ngs/game/GameSearchTest.java
  src/test/java/com/imfine/ngs/publisher/PublisherRegistrationTest.java
Labels: test, refactor

#60 [feat] 팔로우,프로필 기능 구현 및 수정, 컨트롤러 작성
  src/main/java/com/imfine/ngs/_global/config/security/CustomUserDetails.java
  src/main/java/com/imfine/ngs/_global/config/security/CustomUserDetailsService.java
  src/main/java/com/imfine/ngs/user/controller/AuthController.java
  src/main/java/com/imfine/ngs/user/controller/FollowController.java
  src/main/java/com/imfine/ngs/user/controller/ProfileController.java
  src/main/java/com/imfine/ngs/user/controller/UserSupportController.java
  src/main/java/com/imfine/ngs/user/dto/request/FollowRequest.java
  src/main/java/com/imfine/ngs/user/dto/request/ProfileRequest.java
  src/main/java/com/imfine/ngs/user/dto/request/UnfollowRequest.java
  src/main/java/com/imfine/ngs/user/dto/response/FollowResponse.java
  src/main/java/com/imfine/ngs/user/dto/response/ProfileResponse.java
  src/main/java/com/imfine/ngs/user/entity/Follow.java
  src/main/java/com/imfine/ngs/user/entity/User.java
  src/main/java/com/imfine/ngs/user/service/FollowService.java
  src/main/java/com/imfine/ngs/user/service/ProfileService.java
  src/test/java/com/imfine/ngs/publisher/PublisherRegistrationTest.java
  src/test/java/com/imfine/ngs/user/service/FollowServiceTest.java
  src/test/java/com/imfine/ngs/user/service/ProfileServiceTest.java
  src/test/java/com/imfine/ngs/user/service/UserOwnedGameServiceTest.java
Labels: feat

#66 [feat] NGS 메인 화면 컨트롤러와 서비스 간단 구현
  src/main/java/com/imfine/ngs/game/controller/NGSController.java
  src/main/java/com/imfine/ngs/game/controller/search/GameSearchController.java
  src/main/java/com/imfine/ngs/game/service/MainPageService.java
  src/main/java/com/imfine/ngs/game/service/search/GameSearchService.java
  src/test/java/com/imfine/ngs/game/GameControllerTest.java
  src/test/java/com/imfine/ngs/game/NGS/MainPageServiceTest.java
  src/test/java/com/imfine/ngs/game/NGS/NGSControllerTest.java
Labels: add, feat, test

#67 [refector] Community 잘못된 요청 null 반환 -> 예외 처리로 변경
  src/main/java/com/imfine/ngs/community/entity/CommunityBoard.java
  src/main/java/com/imfine/ngs/community/entity/CommunityComment.java
  src/main/java/com/imfine/ngs/community/entity/CommunityPost.java
  src/main/java/com/imfine/ngs/community/entity/TestUser.java
  src/main/java/com/imfine/ngs/community/service/CommunityBoardService.java
  src/main/java/com/imfine/ngs/community/service/CommunityCommentService.java
  src/main/java/com/imfine/ngs/community/service/CommunityPostService.java
  src/test/java/com/imfine/ngs/community/service/CommunityBoardServiceTest.java
  src/test/java/com/imfine/ngs/community/service/CommunityCommentServiceTest.java
  src/test/java/com/imfine/ngs/community/service/CommunityPostServiceTest.java
Labels: refactor

#84 [feat] 게임 아이디로 단일 조회 기능 추가
  src/main/java/com/imfine/ngs/game/controller/search/GameSearchController.java
  src/main/java/com/imfine/ngs/game/repository/GameRepository.java
  src/main/java/com/imfine/ngs/game/service/search/GameSearchService.java
Labels: feat

#85 [fix] security 긴급 수정
  src/main/java/com/imfine/ngs/_global/config/security/SecurityConfig.java
  src/main/java/com/imfine/ngs/user/service/ProfileService.java
Labels: fix

#91 [test] 게임 단일 조회 통과 및 실패 테스트 코드 추가
  src/test/java/com/imfine/ngs/game/GameControllerTest.java
Labels: test

#94 [refactor] SecurityConfig 설정 추가
  src/main/java/com/imfine/ngs/_global/config/security/SecurityConfig.java
  src/main/java/com/imfine/ngs/_global/config/security/jwt/JwtUserPrincipal.java
Labels: refactor

#96 [fix] dto수정
  src/main/java/com/imfine/ngs/user/dto/response/SignInResponse.java
  src/main/java/com/imfine/ngs/user/service/AuthService.java
Labels: fix

#105 [refactor] accessToken을 활용하여 UserId 가져오는 기능 구현
  src/main/java/com/imfine/ngs/support/controller/SupportController.java
  src/main/java/com/imfine/ngs/support/service/SupportService.java
  src/test/java/com/imfine/ngs/support/service/SupportServiceTest.java
Labels: refactor

#110 [refactor] 게임 엔티티에 칼럼을 추가하였다.
  src/main/java/com/imfine/ngs/game/entity/Game.java
Labels: refactor

#123 [refactor] Dto를 Game 도메인에 도입하여 동작하도록 리팩토링 합니다.
  build.gradle
  src/main/java/com/imfine/ngs/game/controller/NGSController.java
  src/main/java/com/imfine/ngs/game/controller/search/GameSearchController.java
  src/main/java/com/imfine/ngs/game/dto/mapper/GameMapper.java
  src/main/java/com/imfine/ngs/game/dto/request/GameCreateRequest.java
  src/main/java/com/imfine/ngs/game/dto/request/GameUpdateRequest.java
  src/main/java/com/imfine/ngs/game/dto/response/GameListResponse.java
  src/main/java/com/imfine/ngs/game/dto/response/GameResponse.java
  src/main/java/com/imfine/ngs/game/dto/response/GameSummaryResponse.java
  src/main/java/com/imfine/ngs/game/dto/response/MainPageResponse.java
  src/main/java/com/imfine/ngs/game/dto/response/PagedSectionResponse.java
  src/main/java/com/imfine/ngs/game/entity/Game.java
  src/main/java/com/imfine/ngs/game/repository/GameRepository.java
  src/main/java/com/imfine/ngs/game/service/MainPageService.java
  src/test/java/com/imfine/ngs/game/GameControllerTest.java
  src/test/java/com/imfine/ngs/game/NGS/GameControllerPageTest.java
  src/test/java/com/imfine/ngs/game/NGS/MainPageServiceTest.java
  src/test/java/com/imfine/ngs/game/NGS/NGSControllerTest.java
  src/test/java/com/imfine/ngs/game/disabled/GameControllerTest.java
Labels: test, refactor

#118 [feat] 닉네임 중복 체크 패스워드 업뎃 수정
  src/main/java/com/imfine/ngs/_global/error/model/ErrorCode.java
  src/main/java/com/imfine/ngs/user/controller/AuthController.java
  src/main/java/com/imfine/ngs/user/dto/request/SignInRequest.java
  src/main/java/com/imfine/ngs/user/dto/request/SignUpRequest.java
  src/main/java/com/imfine/ngs/user/dto/request/UpdatePwdRequest.java
  src/main/java/com/imfine/ngs/user/repository/UserRepository.java
  src/main/java/com/imfine/ngs/user/service/AuthService.java
  src/main/java/com/imfine/ngs/user/service/ProfileService.java
  src/test/java/com/imfine/ngs/user/service/AuthServiceEmailDuplicateUnitTest.java
Labels: feat

#130 [feat]일반 로그인 쿠키 설정 추가
  src/main/java/com/imfine/ngs/_global/config/security/jwt/JwtUserPrincipal.java
  src/main/java/com/imfine/ngs/user/controller/AuthController.java
  src/main/java/com/imfine/ngs/user/controller/UserLibraryController.java
  src/main/java/com/imfine/ngs/user/oauth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/imfine/ngs/user/service/UserLibraryService.java
  src/main/resources/application.yml
  src/test/java/com/imfine/ngs/user/service/UserLibraryServiceTest.java
Labels: refactor

#140 [refactor] 게임 상세 응답을 요구사항에 맞게 수정합니다.
  src/main/java/com/imfine/ngs/game/dto/mapper/GameDetailMapper.java
  src/main/java/com/imfine/ngs/game/dto/response/GameDetailResponse.java
  src/main/java/com/imfine/ngs/game/entity/Game.java
  src/main/java/com/imfine/ngs/game/entity/env/LinkedEnv.java
  src/main/java/com/imfine/ngs/game/enums/EnvType.java
  src/main/java/com/imfine/ngs/game/repository/GameRepository.java
  src/test/java/com/imfine/ngs/game/service/GameServiceTest.java
Labels: test, refactor
