Repository NGSGameCamp/BE_Repository, pull requests merged in 2025-10, with the labels that each got.

#148 refactor: add ResponseDto
  src/main/java/com/imfine/ngs/game/controller/GameRegisterController.java
  src/main/java/com/imfine/ngs/game/dto/request/GameCreateRequest.java
  src/main/java/com/imfine/ngs/game/dto/response/EnvResponse.java
  src/main/java/com/imfine/ngs/game/dto/response/GameCreateResponse.java
  src/main/java/com/imfine/ngs/game/dto/response/GameTagResponse.java
  src/main/java/com/imfine/ngs/game/entity/Game.java
  src/main/java/com/imfine/ngs/game/service/GameRegistrationService.java
Labels: refactor

#151 [fix] 500에러 해결 및 인기도 조회
  src/main/java/com/imfine/ngs/_global/config/security/SecurityConfig.java
  src/main/java/com/imfine/ngs/game/controller/GameController.java
  src/main/java/com/imfine/ngs/game/dto/mapper/GameCardMapper.java
  src/main/java/com/imfine/ngs/game/dto/mapper/GameDetailMapper.java
  src/main/java/com/imfine/ngs/game/dto/mapper/helper/GameMapperHelper.java
  src/main/java/com/imfine/ngs/game/dto/response/GameCardResponse.java
  src/main/java/com/imfine/ngs/game/entity/Game.java
  src/main/java/com/imfine/ngs/game/repository/GameRepository.java
  src/main/java/com/imfine/ngs/game/service/GameRegistrationService.java
  src/main/java/com/imfine/ngs/game/service/GameService.java
  src/main/java/com/imfine/ngs/game/service/support/EnvService.java
  src/main/java/com/imfine/ngs/game/service/support/GameTagService.java
  src/main/java/com/imfine/ngs/game/service/support/LinkedEnvService.java
  src/main/java/com/imfine/ngs/game/service/support/LinkedTagService.java
  src/test/java/com/imfine/ngs/game/NGS/NGSControllerTest.java
  src/test/java/com/imfine/ngs/game/controller/GameControllerPopularTest.java
  src/test/java/com/imfine/ngs/game/service/GameServicePopularTest.java
  src/test/java/com/imfine/ngs/game/service/GameServiceTest.java
Labels: fix, feat, refactor

#162 [fix] 그 녀석(라이브러리 조회 실패) 에러 해결
  src/main/java/com/imfine/ngs/game/service/GameService.java
  src/main/java/com/imfine/ngs/user/controller/UserLibraryController.java
  src/main/java/com/imfine/ngs/user/dto/response/UserLibraryResponse.java
  src/main/java/com/imfine/ngs/user/service/UserLibraryService.java
Labels: fix

#166 [fix] 컴파일, 런타임 에러 해결
  src/main/java/com/imfine/ngs/game/controller/GameController.java
  src/main/java/com/imfine/ngs/game/dto/mapper/GameDetailMapper.java
  src/main/java/com/imfine/ngs/game/repository/GameRepository.java
  src/main/java/com/imfine/ngs/game/service/GameRegistrationService.java
  src/main/java/com/imfine/ngs/game/service/GameService.java
Labels: fix

#168 [fix] 라이브러리 빈 배열 반환 에러 해결
  src/main/java/com/imfine/ngs/game/entity/Game.java
  src/main/java/com/imfine/ngs/game/enums/GameStatusType.java
  src/main/java/com/imfine/ngs/game/repository/GameRepository.java
  src/main/java/com/imfine/ngs/game/service/GameRegistrationService.java
  src/main/java/com/imfine/ngs/user/controller/UserLibraryController.java
  src/main/resources/application.yml
Labels: fix

#169 [fix] 현재까지 발견된 커뮤니티 관련 문제를 수정합니다.
  src/main/java/com/imfine/ngs/_global/config/security/SecurityConfig.java
  src/main/java/com/imfine/ngs/community/controller/CommunityBoardController.java
  src/main/java/com/imfine/ngs/community/controller/CommunityCommentController.java
  src/main/java/com/imfine/ngs/community/controller/mapper/CommunityMapper.java
  src/main/java/com/imfine/ngs/community/dto/response/CommunityBoardResponse.java
  src/main/java/com/imfine/ngs/community/dto/response/CommunityCommentResponse.java
Labels: fix, feat

#177 [refactor] 소셜 로그인 수정, 로그아웃 추가
  src/main/java/com/imfine/ngs/_global/error/GlobalExceptionHandler.java
  src/main/java/com/imfine/ngs/user/controller/AuthController.java
  src/main/java/com/imfine/ngs/user/controller/SocialAuthController.java
  src/main/java/com/imfine/ngs/user/oauth/CookieAuthorizationRequestRepository.java
  src/main/java/com/imfine/ngs/user/oauth/OAuth2AuthenticationFailureHandler.java
  src/main/java/com/imfine/ngs/user/oauth/OAuth2AuthenticationSuccessHandler.java
  src/main/java/com/imfine/ngs/user/service/SocialService.java
  src/main/resources/application.yml
Labels: fix, refactor

#180 [feat] 게임 출시일 조회
  final_database.sql
  src/main/java/com/imfine/ngs/game/controller/GameReleaseController.java
  src/main/java/com/imfine/ngs/game/controller/GameTagController.java
  src/main/java/com/imfine/ngs/game/repository/GameRepository.java
  src/main/java/com/imfine/ngs/game/service/GameReleasedService.java
  src/main/java/com/imfine/ngs/game/service/GameService.java
Labels: add, feat, refactor

#186 [feat] 검색창에서 게임 이름 조회
  src/main/java/com/imfine/ngs/game/controller/GameController.java
  src/main/java/com/imfine/ngs/game/controller/GameTagController.java
  src/main/java/com/imfine/ngs/game/repository/GameRepository.java
  src/main/java/com/imfine/ngs/game/service/GameService.java
Labels: feat, refactor

#188 [feat] 복합 조건 검색 엔드포인트
  build.gradle
  src/main/java/com/imfine/ngs/_global/config/queryDsl/QueryDslConfig.java
  src/main/java/com/imfine/ngs/game/controller/GameController.java
  src/main/java/com/imfine/ngs/game/dto/request/GameSearchRequest.java
  src/main/java/com/imfine/ngs/game/enums/SortType.java
  src/main/java/com/imfine/ngs/game/repository/GameRepository.java
  src/main/java/com/imfine/ngs/game/repository/GameRepositoryImpl.java
  src/main/java/com/imfine/ngs/game/repository/queryDsl/GameRepositoryCustom.java
  src/main/java/com/imfine/ngs/game/service/GameService.java
Labels: add, feat

#192 [refactor] CommunityMapper의 책임을 다른 서비스로 인가했습니다.
  src/main/java/com/imfine/ngs/community/controller/CommunityBoardController.java
  src/main/java/com/imfine/ngs/community/controller/CommunityCommentController.java
  src/main/java/com/imfine/ngs/community/controller/CommunityPostController.java
  src/main/java/com/imfine/ngs/community/controller/mapper/CommunityMapper.java
  src/main/java/com/imfine/ngs/community/service/CommunityTagService.java
  src/main/java/com/imfine/ngs/community/service/CommunityUserService.java
  src/test/java/com/imfine/ngs/community/controller/CommunityPostControllerTest.java
Labels: feat, refactor

#198 [fix] 장바구니 JWT 인증 적용 clearCart 추가
  src/main/java/com/imfine/ngs/order/controller/OrderController.java
  src/main/java/com/imfine/ngs/order/service/OrderService.java
Labels: fix, refactor
